// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsHsoxYlBEu4pFIz1e9ncENVSGRLZCaw',
    appId: '1:747484615155:web:0248b92abbfc06b028c286',
    messagingSenderId: '747484615155',
    projectId: 'venture-link-8cc2e',
    authDomain: 'venture-link-8cc2e.firebaseapp.com',
    storageBucket: 'venture-link-8cc2e.firebasestorage.app',
    measurementId: 'G-J1VT8JB6D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocXPZST3eZxCz9pENt3Kl01MJXJ7bX74',
    appId: '1:747484615155:android:7e6f45b322f5ad7f28c286',
    messagingSenderId: '747484615155',
    projectId: 'venture-link-8cc2e',
    storageBucket: 'venture-link-8cc2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDsCHLIjxJPxR9F1IBC4SZYP3VAS9PBM',
    appId: '1:747484615155:ios:e7c0f7bd3cfcab5328c286',
    messagingSenderId: '747484615155',
    projectId: 'venture-link-8cc2e',
    storageBucket: 'venture-link-8cc2e.firebasestorage.app',
    iosBundleId: 'com.example.ventureLink',
  );
}
